site_name: pgdelta
site_description: PostgreSQL schema differ and DDL generator that produces high-fidelity schema migrations
site_url: https://github.com/olirice/pgdelta
repo_url: https://github.com/olirice/pgdelta
repo_name: olirice/pgdelta
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - API Reference:
    - CLI Interface: api/cli.md
    - Python API: api/python.md
    - Planned API: api/planned.md
  - Supported Entities:
    - Overview: entities/overview.md
    - Schemas: entities/schemas.md
    - Tables: entities/tables.md
    - Constraints: entities/constraints.md
    - Indexes: entities/indexes.md
    - Views: entities/views.md
    - Materialized Views: entities/materialized-views.md
    - Functions: entities/functions.md
    - Triggers: entities/triggers.md
    - Sequences: entities/sequences.md
    - Types: entities/types.md
    - Policies: entities/policies.md
  - Architecture: architecture.md
  - Dependency Resolution: dependency-resolution.md
  - Contributing:
    - Setup & Guidelines: contributing/setup.md
    - Adding New Entities: contributing/adding-entities.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/olirice/pgdelta
